### ISSUE TITLE
Set up a production environment in Virtual Wall

### ISSUE THREAD

**Issue by julianrojas87** [linkedtimeseries/AirQualityExpressServer#6]

**Comment by brechtvdv** [comment]
I would suggest to set this up on my permanent LODI server on the virtuall wall.
This is a 1-node server, so Kubernetes is not applicable here.

**Comment by brechtvdv** [comment]
Let me know when its docker(-compose) ready and I'll give it a spin

**Comment by brechtvdv** [comment]
Deployed on https://lodi.ilabt.imec.be/air

Example query: https://lodi.ilabt.imec.be/air/data/14/8392/5467?page=2019-08-06T00:00:00.000Z
